version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tasks
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - task-app-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    - "443:443"
    networks:
    - task-app-network

  task-service:
    image: openjdk:8-jre
    container_name: task-service
    volumes:
    - ./target/oracle-task-app-1.0.0-SNAPSHOT.jar:/taskservice/oracle-task-app-1.0.0-SNAPSHOT.jar
    - ./configuration.yml:/taskservice/configuration.yml
    working_dir: /taskservice
    command: ["java", "-jar", "oracle-task-app-1.0.0-SNAPSHOT.jar", "server", "configuration.yml"]
    ports:
    - "8090:8080"
    - "8091:8081"
    networks:
    - task-app-network

networks:
  task-app-network:
    external:
      name: task-app-network